# Generated by Django 5.2.7 on 2025-10-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_created_at_restaurant_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='Особые пожелания'),
        ),
    ]
