# Generated by Django 5.2.7 on 2025-10-27 12:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservation_options_alter_restaurant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-reservation_date', '-reservation_time'], 'verbose_name': 'бронирование', 'verbose_name_plural': 'бронирования'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'ресторан', 'verbose_name_plural': 'рестораны'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_number'], 'verbose_name': 'столик', 'verbose_name_plural': 'столики'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, verbose_name='веб-сайт'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guests_count',
            field=models.IntegerField(verbose_name='количество гостей'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(verbose_name='дата бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.TimeField(verbose_name='время бронирования'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='special_requests',
            field=models.TextField(blank=True, verbose_name='особые пожелания'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Подтверждено'), ('pending', 'Ожидание'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(verbose_name='адрес'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('italian', 'Итальянская'), ('japanese', 'Японская'), ('russian', 'Русская'), ('french', 'Французская'), ('chinese', 'Китайская'), ('georgian', 'Грузинская'), ('american', 'Американская')], max_length=50, verbose_name='тип кухни'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/%Y/%m/%d/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.CharField(default='10:00-22:00', max_length=100, verbose_name='часы работы'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='телефон'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(verbose_name='вместимость'),
        ),
        migrations.AlterField(
            model_name='table',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=500.0, max_digits=8, verbose_name='цена за час'),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.CharField(max_length=10, verbose_name='номер столика'),
        ),
        migrations.CreateModel(
            name='RestaurantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='restaurants/documents/%Y/%m/%d/', verbose_name='документ')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'документ ресторана',
                'verbose_name_plural': 'документы ресторанов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='restaurant.tag', verbose_name='теги'),
        ),
    ]
